name: Install a binary from GitHub Releases
description: Easily install a binary from a GitHub Release that works across repositories in Rust, Go, C++, and more.
author: sigoden <sigoden@gmail.com>
branding:
  icon: box
  color: green
inputs:
  repo:
    description: The GitHub repository in `owner/repo` format
    required: true
  tag:
    description: The release tag to download
    default: latest
  name:
    description: The specific binary name within the release
  cache:
    description: Controls whether the binary is cached
    default: false
  token:
    description: GitHub token, useful for private repositories
    default: ${{ github.token }}
runs:
  using: node20
  main: dist/index.js