name: build

on:
  push:
  schedule:
    - cron: 0 12 1 * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: npm ci
    - run: npm run lint
    - run: npm run build

  test-install-argc:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install binary
      uses: ./
      with:
        repo: sigoden/argc
    - name: Test
      run: |
        argc --argc-version
      shell: bash

  test-install-argc-with-tag:
    needs: test-install-argc
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install binary
      uses: ./
      with:
        repo: sigoden/argc
        tag: v1.16.0
    - name: Test
      run: |
        [ "$(argc --argc-version)" == "argc 1.16.0" ]
      shell: bash

  test-install-task:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install binary
      uses: ./
      with:
        repo: go-task/task
    - name: Test
      run: |
        task --version
      shell: bash

  test-install-wasm-opt:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install binary
      uses: ./
      with:
        repo: WebAssembly/binaryen
        name: wasm-opt
    - name: Test
      run: |
        wasm-opt --version
      shell: bash